version: '3.4'

services:
  product:
    container_name: e-commerce_product
    build: 
      context: ./product
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - e-commerce_network
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:latest
    container_name: e-commerce_cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=e-commerce_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - 9042:9042  # Cassandra default port
    networks:
      - e-commerce_network
    volumes:
      - cassandra-data:/var/lib/cassandra  # Mount volume for persistent data
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=142536
      - POSTGRES_DB=order
    networks:
      - e-commerce_network
    volumes:
    - ./order/order.sql:/docker-entrypoint-initdb.d/order.sql

networks:
  e-commerce_network:
    driver: bridge
    
volumes:
  cassandra-data:
    driver: local  # Make sure to define the volume here
