apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Les valeurs sont encodées en base64
  # Pour postgres/142536:
  username: cG9zdGdyZXM=      # postgres en base64
  password: MTQyNTM2          # 142536 en base64
